import os
import subprocess
from pathlib import Path

from garaga.curves import CurveID, ProofSystem
from garaga.modulo_circuit_structs import G2Line, StructArray
from garaga.precompiled_circuits.multi_miller_loop import precompute_lines
from garaga.starknet.cli.utils import create_directory, get_package_version
from garaga.starknet.constants import CAIRO_VERSION, STARKNET_FOUNDRY_VERSION
from garaga.starknet.groth16_contract_generator.calldata import (
    groth16_calldata_from_vk_and_proof,
)
from garaga.starknet.groth16_contract_generator.parsing_utils import (
    Groth16Proof,
    Groth16VerifyingKey,
)

ECIP_OPS_CLASS_HASH = 0x312D1DD5F967EAF6F86965E3FA7ACBC9D0FBD979066A17721DD913736AF2F5E


def precompute_lines_from_vk(vk: Groth16VerifyingKey) -> StructArray:

    # Precompute lines for fixed G2 points
    lines = precompute_lines([vk.gamma, vk.delta])
    precomputed_lines = StructArray(
        name="lines",
        elmts=[
            G2Line(name=f"line{i}", elmts=lines[i : i + 4])
            for i in range(0, len(lines), 4)
        ],
    )

    return precomputed_lines

def precompute_lines_from_vk_groth16(vk: Groth16VerifyingKey) -> (StructArray, StructArray):

    # Precompute lines for fixed G2 points
    lines = precompute_lines([vk.commitment_key_g_root_sigma_neg, vk.commitment_key_g])
    precomputed_lines = StructArray(
        name="lines",
        elmts=[
            G2Line(name=f"line{i}", elmts=lines[i : i + 4])
            for i in range(0, len(lines), 4)
        ],
    )

    return precompute_lines_from_vk(vk), precomputed_lines


def gen_test_file(
    contract_name: str,
    verifier_name: str,
    system: ProofSystem,
    verification_function_name: str,
    package_name: str,
    rpc_url: str = "https://rpc.starknet-testnet.lava.build:443",
):
    code = f"""
//! # Starknet Verification Contract Tests
//!
//! This module contains comprehensive tests for the proof verification contract.
//! The tests use Starknet Foundry's testing features to verify proofs.
//!
//! ## Test Strategy
//! - Use real proof fixtures generated by the garaga CLI
//! - Test both positive (valid proof) and negative (invalid proof) cases

use snforge_std::fs::{{FileTrait, read_txt}};
use snforge_std::{{DeclareResultTrait, declare}};
use {package_name}::{verifier_name}::{{
    I{contract_name}LibraryDispatcher, I{contract_name}DispatcherTrait,
}};
use starknet::ClassHash;

/// Declare the {contract_name} contract for testing.
///
/// This function declares a new instance of the {contract_name} contract
///
/// # Arguments
/// * `name` - The contract name to declare
///
/// # Returns
/// * `ClassHash` - The class hash of the declared contract
///
/// # Example
/// ```cairo
/// let class_hash = declare_contract("{contract_name}");
/// let dispatcher = I{contract_name}LibraryDispatcher {{ class_hash }};
/// ```
fn declare_contract(name: ByteArray) -> ClassHash {{
    let class_hash = *declare(name).unwrap().contract_class().class_hash;
    class_hash
}}

/// Test the verification function {verification_function_name} with a valid proof.
///
/// This test demonstrates the complete verification flow:
/// 1. Declare the verification contract
/// 2. Load a pre-generated proof fixture
/// 3. Verify the proof on-chain
/// 4. Assert that verification succeeds
///
/// ## Test Setup
/// - Uses fork testing against Sepolia testnet to access required declared contracts maintained by the garaga team
/// - Loads proof calldata from `tests/proof_calldata.txt`
/// - To generate the calldata, you can use the garaga CLI:
/// ```bash
/// garaga calldata
///     --system {system.value}
///     --vk path/to/vk
///     --proof path/to/proof
///     --public-inputs path/to/public_inputs
///     --format snforge
///     --output-path path/to/tests
/// ```
/// This will generate a file `proof_calldata.txt` in the specified output path.
/// You can then use this file in the test.
///
/// ## Expected Behavior
/// - The proof should verify successfully
/// - The function should return Ok(public_inputs) containing the expected public inputs
/// - No panics or assertion failures should occur
#[test]
#[fork(url: "{rpc_url}", block_tag: latest)]
fn test_{verification_function_name}() {{
    // Step 1: Declare the verification contract
    let class_hash = declare_contract("{contract_name}");
    let dispatcher = I{contract_name}LibraryDispatcher {{ class_hash }};

    // Step 2: Load the proof fixture generated by the script
    // This file contains the {system.value} proof calldata formatted for Starknet
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    // Step 3: Verify the proof on-chain
    // This calls the contract's {verification_function_name} function with the loaded proof data
    let result = dispatcher.{verification_function_name}(calldata);

    // Step 4: Assert that verification succeeded
    // A valid proof should return Ok(public_inputs), not Err
    assert(result.is_ok(), 'Proof verification failed');

    // Optional: You can also verify the public inputs contain expected values
    // let public_inputs = result.unwrap();
    // assert(public_inputs.len() > 0, 'No public inputs');
    // Additional assertions on the public input values can be added here
}}
"""
    return code


def get_scarb_toml_file(package_name: str, cli_mode: bool, inlining_level: int = 2):
    version = get_package_version()
    header = f"# Generated by Garaga version {version}\n"
    if version == "dev":
        suffix = ""
    else:
        suffix = ', tag = "v' + version + '"'
    if cli_mode:
        dep = 'git = "https://github.com/keep-starknet-strange/garaga.git"' + suffix
    else:
        dep = 'path = "../../../"'

    return (
        header
        + f"""[package]
name = "{package_name}"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = {{ {dep} }}
starknet = "{CAIRO_VERSION}"

[cairo]
sierra-replace-ids = false
inlining-strategy = {inlining_level}

[dev-dependencies]
snforge_std = "{STARKNET_FOUNDRY_VERSION}"
assert_macros = "{CAIRO_VERSION}"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
"""
    )


def write_test_calldata_file(
    output_folder_path: str,
    vk: Groth16VerifyingKey,
    proof: Groth16Proof,
) -> None:
    """Write the test calldata file for a given verifying key and proof."""
    tests_dir = os.path.join(output_folder_path, "tests")
    cd = groth16_calldata_from_vk_and_proof(vk, proof)
    with open(os.path.join(tests_dir, "proof_calldata.txt"), "w") as f:
        for x in cd[1:]:
            f.write(f"{hex(x)}\n")


def create_verifier_directory_structure(
    output_folder_path: str, include_test_sample: bool = True
) -> tuple[str, str]:
    """Create the standard directory structure for a verifier contract.

    Returns:
        tuple: (src_dir, tests_dir) paths
    """
    create_directory(output_folder_path)
    src_dir = os.path.join(output_folder_path, "src")
    tests_dir = (
        os.path.join(output_folder_path, "tests") if include_test_sample else None
    )
    create_directory(src_dir)
    if include_test_sample:
        create_directory(tests_dir)
    return src_dir, tests_dir


def write_tool_versions_file(output_folder_path: str) -> None:
    """Write the .tool-versions file."""
    with open(os.path.join(output_folder_path, ".tool-versions"), "w") as f:
        f.write(f"scarb {CAIRO_VERSION}\n")
        f.write(f"starknet-foundry {STARKNET_FOUNDRY_VERSION}\n")


def write_lib_cairo_file(src_dir: str, modules: list[str] = None) -> None:
    """Write the lib.cairo file with specified modules."""
    if modules is None:
        modules = ["groth16_verifier", "groth16_verifier_constants"]

    module_imports = "\n".join(f"pub mod {module};" for module in modules)
    with open(os.path.join(src_dir, "lib.cairo"), "w") as f:
        version = get_package_version()
        header = f"// Generated by Garaga version {version}\n"
        f.write(header + f"\n{module_imports}\n")


def write_verifier_files(
    output_folder_path: str,
    package_name: str,
    constants_code: str | None,
    contract_code: str,
    contract_cairo_name: str,
    verification_function_name: str,
    system: ProofSystem,
    cli_mode: bool = False,
    circuits_code: str | None = None,
    modules: list[str] = None,
    constants_filename: str = "groth16_verifier_constants.cairo",
    contract_filename: str = "groth16_verifier.cairo",
    circuits_filename: str | None = None,
    include_test_sample: bool = True,
    constants_output_path: str | None = None,
) -> None:
    """Write all the standard verifier files (directories, constants, contract, scarb.toml, lib.cairo, test files)."""

    # Create directory structure
    src_dir, tests_dir = create_verifier_directory_structure(
        output_folder_path, include_test_sample
    )

    # Write tool versions
    write_tool_versions_file(output_folder_path)

    # Build header once for Cairo files
    version = get_package_version()
    header_cairo = f"// Generated by Garaga version {version}\n"

    # Write Scarb.toml
    with open(os.path.join(output_folder_path, "Scarb.toml"), "w") as f:
        f.write(get_scarb_toml_file(package_name, cli_mode))

    # Write lib.cairo
    write_lib_cairo_file(src_dir, modules)

    # Write constants file (if requested)
    if constants_code is not None:
        target_constants_path = constants_output_path or os.path.join(
            src_dir, constants_filename
        )
        target_constants_dir = os.path.dirname(target_constants_path)
        os.makedirs(target_constants_dir, exist_ok=True)
        with open(target_constants_path, "w") as f:
            f.write(header_cairo + constants_code)

        subprocess.run(["scarb", "fmt", "."], cwd=target_constants_dir, check=True)

    # Write contract file
    with open(os.path.join(src_dir, contract_filename), "w") as f:
        f.write(header_cairo + contract_code)

    # Write circuits file if provided
    if circuits_code and circuits_filename:
        with open(os.path.join(src_dir, circuits_filename), "w") as f:
            f.write(header_cairo + circuits_code)

    # Write test file.
    if include_test_sample:
        with open(os.path.join(tests_dir, "test_contract.cairo"), "w") as f:
            f.write(
                header_cairo
                + gen_test_file(
                    contract_cairo_name,
                    contract_filename.removesuffix(".cairo"),
                    system,
                    verification_function_name,
                    package_name,
                )
            )
    subprocess.run(["scarb", "fmt", "."], cwd=output_folder_path, check=True)


def write_test_calldata_file_generic(
    output_folder_path: str,
    system: ProofSystem,
    vk_path: str,
    proof_path: str,
    public_inputs_path: str = None,
) -> None:
    """Write the test calldata file for any proof system using get_calldata_generic."""
    from pathlib import Path as PathType

    from garaga.starknet.cli.verify import get_calldata_generic

    tests_dir = os.path.join(output_folder_path, "tests")
    cd = get_calldata_generic(
        system,
        PathType(vk_path),
        PathType(proof_path),
        PathType(public_inputs_path) if public_inputs_path else None,
    )
    with open(os.path.join(tests_dir, "proof_calldata.txt"), "w") as f:
        for x in cd[1:]:
            f.write(f"{hex(x)}\n")


def gen_groth16_verifier(
    vk: str | Path | Groth16VerifyingKey,
    output_folder_path: str,
    output_folder_name: str,
    ecip_class_hash: int = ECIP_OPS_CLASS_HASH,
    cli_mode: bool = False,
    include_test_sample: bool = True,
) -> str:
    if isinstance(vk, (Path, str)):
        vk = Groth16VerifyingKey.from_json(vk)
    else:
        vk = vk

    curve_id = vk.curve_id
    if cli_mode:
        output_folder_name = output_folder_name
    else:
        output_folder_name = output_folder_name + f"_{curve_id.name.lower()}"
    output_folder_path = os.path.join(output_folder_path, output_folder_name)

    precomputed_lines, commitment_precomputed_lines = precompute_lines_from_vk_groth16(vk)
    verification_function_name = f"verify_groth16_proof_{curve_id.name.lower()}"
    contract_cairo_name = f"Groth16Verifier{curve_id.name}"
    constants_code = f"""
    use garaga::definitions::{{G1Point, G2Point, E12D, G2Line, u384}};
    {f"use garaga::definitions::u288;" if curve_id!=CurveID.BLS12_381 else ""}
    use garaga::groth16::Groth16VerifyingKey;

    pub const N_PUBLIC_INPUTS:usize = {len(vk.ic)-1};
    {vk.serialize_to_cairo()}
    pub const precomputed_lines: [G2Line; {len(precomputed_lines)//4}] = {precomputed_lines.serialize(raw=True, const=True)};
    pub const commitment_precomputed_lines: [G2Line; {len(commitment_precomputed_lines)//4}] = {commitment_precomputed_lines.serialize(raw=True, const=True)};
    """
    print(constants_code)
    contract_code = f"""
use garaga::definitions::G1Point;
use garaga::groth16::Groth16Proof;
use super::groth16_verifier_constants::{{N_PUBLIC_INPUTS, vk, ic, precomputed_lines, commitment_precomputed_lines, pedersen_g, pedersen_g_root_sigma_neg}};
use garaga::pairing_check::MPCheckHintBN254;

#[derive(Drop)]
pub struct FullProofWithHints {{
    pub groth16_proof: Groth16Proof,
    pub proof_commitment: G1Point,
    pub proof_commitment_pok: G1Point,
    pub mpcheck_hint: MPCheckHintBN254,
    pub msm_hint: Span<felt252>,
    pub commitment_mpcheck_hint: MPCheckHintBN254,
}}

#[starknet::interface]
pub trait I{contract_cairo_name}<TContractState> {{
    fn {verification_function_name}(
        self: @TContractState,
        full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
}}

#[starknet::contract]
mod {contract_cairo_name} {{
    use core::circuit::u384;
    use starknet::SyscallResultTrait;
    #[feature("bounded-int-utils")]
    use core::internal::bounded_int::downcast;
    use garaga::definitions::{{E12D, G1Point, G1G2Pair, u288}};
    use garaga::groth16::{{multi_pairing_check_{curve_id.name.lower()}_3P_2F_with_extra_miller_loop_result, Groth16ProofRawTrait}};
    use garaga::ec_ops::{{G1PointTrait, ec_safe_add}};
    use garaga::utils::calldata::{{_deserialize_E12D_u288, _deserialize_groth16_proof_points}};
    use garaga::pairing_check::{{MillerLoopResultScalingFactor, multi_pairing_check_bn254_2P_2F}};
    use super::{{FullProofWithHints, Groth16Proof, N_PUBLIC_INPUTS, vk, ic, precomputed_lines, commitment_precomputed_lines, pedersen_g, pedersen_g_root_sigma_neg, MPCheckHintBN254}};

    const ECIP_OPS_CLASS_HASH: felt252 = {hex(ecip_class_hash)};

    #[storage]
    struct Storage {{}}

    #[abi(embed_v0)]
    impl IGroth16Verifier{curve_id.name} of super::IGroth16Verifier{curve_id.name}<ContractState> {{
        fn {verification_function_name}(
            self: @ContractState,
            full_proof_with_hints: Span<felt252>,
        ) -> Result<Span<u256>, felt252> {{
            // DO NOT EDIT THIS FUNCTION UNLESS YOU KNOW WHAT YOU ARE DOING.
            // This function returns Result::Ok(public_inputs) if the proof is valid.
            // If the proof is invalid, it returns Result::Err(error).
            // Read the documentation to learn how to generate the full_proof_with_hints array given a proof and a verifying key.
            let fph = deserialize_full_proof_with_hints_{curve_id.name.lower()}(full_proof_with_hints);
            let groth16_proof = fph.groth16_proof;
            let mpcheck_hint = fph.mpcheck_hint;
            let msm_hint = fph.msm_hint;
            let mut commitment_mpcheck_hint = fph.commitment_mpcheck_hint;

            groth16_proof.raw.check_proof_points({curve_id.value});

            let ic = ic.span();

            let vk_x: G1Point = match ic.len() {{
                0 => panic!("Malformed VK"),
                1 => *ic.at(0),
                _ => {{
                    // Start serialization with the hint array directly to avoid copying it.
                    let mut msm_calldata: Array<felt252> = array![];
                    // Add the points from VK and public inputs to the proof.
                    Serde::serialize(@ic.slice(1, N_PUBLIC_INPUTS), ref msm_calldata);
                    Serde::serialize(@groth16_proof.public_inputs, ref msm_calldata);
                    // Complete with the curve indentifier ({curve_id.value} for {curve_id.name}):
                    msm_calldata.append({curve_id.value});
                    // Add the hint array.
                    for x in msm_hint {{
                        msm_calldata.append(*x);
                    }}

                    // Call the multi scalar multiplication endpoint on the Garaga ECIP ops contract
                    // to obtain vk_x.
                    let mut _vx_x_serialized = starknet::syscalls::library_call_syscall(
                        ECIP_OPS_CLASS_HASH.try_into().unwrap(),
                        selector!("msm_g1"),
                        msm_calldata.span()
                    )
                        .unwrap_syscall();

                    ec_safe_add(
                        Serde::<G1Point>::deserialize(ref _vx_x_serialized).unwrap(),
                        ec_safe_add(*ic.at(0), fph.proof_commitment, 0),
                        0,
                    )
                }}
            }};
            // Perform the pairing check.
            let check = multi_pairing_check_{curve_id.name.lower()}_3P_2F_with_extra_miller_loop_result(
                G1G2Pair {{ p: vk_x, q: vk.gamma_g2 }},
                G1G2Pair {{ p: groth16_proof.raw.c, q: vk.delta_g2 }},
                G1G2Pair {{ p: groth16_proof.raw.a.negate({curve_id.value}), q: groth16_proof.raw.b }},
                vk.alpha_beta_miller_loop_result,
                precomputed_lines.span(),
                mpcheck_hint,
            );
            let res = multi_pairing_check_bn254_2P_2F(
                G1G2Pair {{ p: fph.proof_commitment, q: pedersen_g }},
                G1G2Pair {{ p: fph.proof_commitment_pok, q: pedersen_g_root_sigma_neg }},
                commitment_precomputed_lines.span(),
                commitment_mpcheck_hint,
            )?;

            if !res {{
                return Result::Err('PAIRING_CHECK_FAILED');
            }}

            match check {{
                Result::Ok(_) => Result::Ok(groth16_proof.public_inputs),
                Result::Err(error) => Result::Err(error),
            }}
        }}
    }}

    #[inline(always)]
    fn downcast_u288(l0: felt252, l1: felt252, l2: felt252) -> u288 {{
        u288 {{
            limb0: downcast(l0).unwrap(),
            limb1: downcast(l1).unwrap(),
            limb2: downcast(l2).unwrap(),
        }}
    }}

    #[inline(always)]
    fn downcast_u384(l0: felt252, l1: felt252, l2: felt252, l3: felt252) -> u384 {{
        u384 {{
            limb0: downcast(l0).unwrap(),
            limb1: downcast(l1).unwrap(),
            limb2: downcast(l2).unwrap(),
            limb3: downcast(l3).unwrap(),
        }}
    }}

    #[inline(always)]
    pub fn deserialize_full_proof_with_hints_bn254(mut serialized: Span<felt252>) -> FullProofWithHints {{
        let groth16_proof_raw = _deserialize_groth16_proof_points(ref serialized);

        let n_public_inputs: u32 = (*serialized.pop_front().unwrap()).try_into().unwrap();
        let mut public_inputs = array![];
        for _ in 0..n_public_inputs {{
            public_inputs
                .append(
                    u256 {{
                        low: (*serialized.pop_front().unwrap()).try_into().unwrap(),
                        high: (*serialized.pop_front().unwrap()).try_into().unwrap(),
                    }},
                );
        }}

        let groth16_proof = Groth16Proof {{
            raw: groth16_proof_raw, public_inputs: public_inputs.span(),
        }};

        let [
            poc_x_0,
            poc_x_1,
            poc_x_2,
            poc_x_3,
            poc_y_0,
            poc_y_1,
            poc_y_2,
            poc_y_3,
            pok_x_0,
            pok_x_1,
            pok_x_2,
            pok_x_3,
            pok_y_0,
            pok_y_1,
            pok_y_2,
            pok_y_3,
        ] =
            serialized
            .multi_pop_front::<16>()
            .unwrap()
            .unbox();
        let proof_commitment = G1Point {{
            x: downcast_u384(poc_x_0, poc_x_1, poc_x_2, poc_x_3),
            y: downcast_u384(poc_y_0, poc_y_1, poc_y_2, poc_y_3),
        }};
        let proof_commitment_pok = G1Point {{
            x: downcast_u384(pok_x_0, pok_x_1, pok_x_2, pok_x_3),
            y: downcast_u384(pok_y_0, pok_y_1, pok_y_2, pok_y_3),
        }};

        let mpcheck_hint = deserialize_mpcheck_hint_bn254(ref serialized, 190);
        let commitment_mpcheck_hint = deserialize_mpcheck_hint_bn254(ref serialized, 145);

        let msm_hint = serialized;

        return FullProofWithHints {{
            groth16_proof,
            proof_commitment,
            proof_commitment_pok,
            mpcheck_hint,
            commitment_mpcheck_hint,
            msm_hint,
        }};
    }}

    pub fn deserialize_mpcheck_hint_bn254(
        ref serialized: Span<felt252>, big_q_len: u32,
    ) -> MPCheckHintBN254 {{
        let lambda_root = _deserialize_E12D_u288(ref serialized);
        let lambda_root_inverse = _deserialize_E12D_u288(ref serialized);

        let [
            w0_l0,
            w0_l1,
            w0_l2,
            w2_l0,
            w2_l1,
            w2_l2,
            w4_l0,
            w4_l1,
            w4_l2,
            w6_l0,
            w6_l1,
            w6_l2,
            w8_l0,
            w8_l1,
            w8_l2,
            w10_l0,
            w10_l1,
            w10_l2,
        ] =
            (*serialized
            .multi_pop_front::<18>()
            .unwrap())
            .unbox();

        // full_len -= 18;
        // assert(full_len == serialized.len(), 'F');

        let w = MillerLoopResultScalingFactor {{
            w0: downcast_u288(w0_l0, w0_l1, w0_l2),
            w2: downcast_u288(w2_l0, w2_l1, w2_l2),
            w4: downcast_u288(w4_l0, w4_l1, w4_l2),
            w6: downcast_u288(w6_l0, w6_l1, w6_l2),
            w8: downcast_u288(w8_l0, w8_l1, w8_l2),
            w10: downcast_u288(w10_l0, w10_l1, w10_l2),
        }};
        // usize_assert_eq(mpcheck_hint.Ris.len(), 34);
        // 34 * 12 * 3 = 1224
        let mut ris_slice = serialized.slice(1, 1224);
        // println!("ris_slice.len(): {{}}", ris_slice.len());

        let end = serialized.len();
        serialized = serialized.slice(1225, end - 1224 - 1);
        // println!("serialized.len(): {{}}", serialized.len());
        let mut Ris = array![];
        while let Option::Some(ri) = ris_slice.multi_pop_front::<36>() {{
            let [
                w0l0,
                w0l1,
                w0l2,
                w1l0,
                w1l1,
                w1l2,
                w2l0,
                w2l1,
                w2l2,
                w3l0,
                w3l1,
                w3l2,
                w4l0,
                w4l1,
                w4l2,
                w5l0,
                w5l1,
                w5l2,
                w6l0,
                w6l1,
                w6l2,
                w7l0,
                w7l1,
                w7l2,
                w8l0,
                w8l1,
                w8l2,
                w9l0,
                w9l1,
                w9l2,
                w10l0,
                w10l1,
                w10l2,
                w11l0,
                w11l1,
                w11l2,
            ] =
                (*ri)
                .unbox();
            Ris
                .append(
                    E12D {{
                        w0: downcast_u288(w0l0, w0l1, w0l2),
                        w1: downcast_u288(w1l0, w1l1, w1l2),
                        w2: downcast_u288(w2l0, w2l1, w2l2),
                        w3: downcast_u288(w3l0, w3l1, w3l2),
                        w4: downcast_u288(w4l0, w4l1, w4l2),
                        w5: downcast_u288(w5l0, w5l1, w5l2),
                        w6: downcast_u288(w6l0, w6l1, w6l2),
                        w7: downcast_u288(w7l0, w7l1, w7l2),
                        w8: downcast_u288(w8l0, w8l1, w8l2),
                        w9: downcast_u288(w9l0, w9l1, w9l2),
                        w10: downcast_u288(w10l0, w10l1, w10l2),
                        w11: downcast_u288(w11l0, w11l1, w11l2),
                    }},
                )
        }}
        // usize_assert_eq(mpcheck_hint.big_Q.len(), 190);
        let mut big_q_slice = serialized.slice(1, big_q_len * 3);
        let end = serialized.len();
        serialized = serialized.slice(big_q_len * 3 + 1, end - big_q_len * 3 - 1);
        let mut big_q = array![];
        while let Option::Some(q) = big_q_slice.multi_pop_front::<3>() {{
            let [l0, l1, l2] = (*q).unbox();
            big_q.append(downcast_u288(l0, l1, l2))
        }}

        let z = (*serialized.pop_front().unwrap()).try_into().unwrap();

        let mpcheck_hint = MPCheckHintBN254 {{
            lambda_root: lambda_root,
            lambda_root_inverse: lambda_root_inverse,
            w: w,
            Ris: Ris.span(),
            big_Q: big_q,
            z: z,
        }};
        return mpcheck_hint;
    }}

}}


    """

    # Use the new reusable function to write all files
    write_verifier_files(
        output_folder_path,
        output_folder_name,
        constants_code,
        contract_code,
        contract_cairo_name,
        verification_function_name,
        ProofSystem.Groth16,
        cli_mode,
        include_test_sample=include_test_sample,
    )

    return constants_code


if __name__ == "__main__":

    EXAMPLES_FOLDER = "hydra/garaga/starknet/groth16_contract_generator/examples"
    vk_paths = [
        os.path.join(EXAMPLES_FOLDER, "vk_bn254.json"),
        os.path.join(EXAMPLES_FOLDER, "vk_bls.json"),
    ]
    proof_paths = [
        os.path.join(EXAMPLES_FOLDER, "proof_bn254.json"),
        os.path.join(EXAMPLES_FOLDER, "proof_bls.json"),
    ]

    CONTRACTS_FOLDER = "src/contracts/autogenerated/"  # Do not change this

    FOLDER_NAME = "groth16_example"  # '_curve_id' is appended in the end.

    def _generate_verifier(vk_path):
        try:
            gen_groth16_verifier(
                vk_path, CONTRACTS_FOLDER, FOLDER_NAME, ECIP_OPS_CLASS_HASH
            )
        except Exception as e:
            print(f"An error occurred: {e}")
            raise e

    for vk_path in vk_paths:
        _generate_verifier(vk_path)

    FOLDER_NAMES = [f"groth16_example_bn254", "groth16_example_bls12_381"]
    for contract_name, vk_path, proof_path in zip(FOLDER_NAMES, vk_paths, proof_paths):
        vk = Groth16VerifyingKey.from_json(vk_path)
        proof = Groth16Proof.from_json(proof_path=proof_path)
        output_folder_path = os.path.join(CONTRACTS_FOLDER, contract_name)
        write_test_calldata_file_generic(
            output_folder_path,
            system=ProofSystem.Groth16,
            vk_path=vk_path,
            proof_path=proof_path,
        )
